import 'dart:math' as math;

class LocalDemoData {
  static Map<String, dynamic> snapshot({
    required double south,
    required double west,
    required double north,
    required double east,
  }) {
    final now = DateTime.now().toUtc().toIso8601String();
    final redZones = <Map<String, dynamic>>[
      {
        'zone_id': 'ODCY_RZ_01',
        'grid_id': 'ODCY_GRID_01',
        'latitude': 20.34,
        'longitude': 86.62,
        'risk_score': 92.0,
        'is_red_zone': true,
        'risk_level': 'CRITICAL',
        'hazard_type': 'COASTAL_EROSION',
        'geometry_wkt': 'POLYGON((86.46 20.18, 86.78 20.18, 86.86 20.36, 86.76 20.52, 86.42 20.48, 86.46 20.18))',
        'prediction_timestamp': now,
        'model_version': 'bundled-demo-1.0',
        'time_horizon': 'IMMEDIATE',
      },
      {
        'zone_id': 'ODCY_RZ_02',
        'grid_id': 'ODCY_GRID_02',
        'latitude': 20.18,
        'longitude': 86.21,
        'risk_score': 84.0,
        'is_red_zone': true,
        'risk_level': 'CRITICAL',
        'hazard_type': 'FLOOD',
        'geometry_wkt': 'POLYGON((86.02 20.00, 86.34 19.98, 86.42 20.14, 86.28 20.31, 86.00 20.26, 86.02 20.00))',
        'prediction_timestamp': now,
        'model_version': 'bundled-demo-1.0',
        'time_horizon': 'IMMEDIATE',
      },
      {
        'zone_id': 'ODCY_RZ_03',
        'grid_id': 'ODCY_GRID_03',
        'latitude': 19.93,
        'longitude': 85.95,
        'risk_score': 68.0,
        'is_red_zone': true,
        'risk_level': 'HIGH',
        'hazard_type': 'FLOOD',
        'geometry_wkt': 'POLYGON((85.76 19.80, 86.08 19.78, 86.16 19.94, 86.00 20.09, 85.74 20.00, 85.76 19.80))',
        'prediction_timestamp': now,
        'model_version': 'bundled-demo-1.0',
        'time_horizon': 'SHORT_TERM',
      },
    ];

    final habitations = <Map<String, dynamic>>[
      {
        'habitation_id': 'OD_HAB_001',
        'state_code': 'OD',
        'district_name': 'Kendrapara',
        'village_name': 'Satabhaya',
        'latitude': 20.61,
        'longitude': 86.89,
        'total_population': 3620,
        'male_population': 1810,
        'female_population': 1810,
        'population_0_6': 470,
        'population_60_plus': 392,
        'literacy_rate': 69.0,
        'priority_score': 91.0,
        'priority_category': 'IMMEDIATE',
        'expert_category': 'IMMEDIATE',
        'ml_category': 'IMMEDIATE',
        'proximity_to_hazard_km': 0.6,
        'elevation': 4.0,
        'slope_percentage': 0.3,
        'has_access_road': true,
        'path_status': 'DAMAGED',
        'geometry_wkt': 'POINT(86.89 20.61)',
        'assessment_timestamp': now,
        'model_version': 'bundled-demo-1.0',
      },
      {
        'habitation_id': 'OD_HAB_002',
        'state_code': 'OD',
        'district_name': 'Jagatsinghpur',
        'village_name': 'Erasama',
        'latitude': 20.20,
        'longitude': 86.39,
        'total_population': 4980,
        'male_population': 2490,
        'female_population': 2490,
        'population_0_6': 610,
        'population_60_plus': 510,
        'literacy_rate': 72.0,
        'priority_score': 83.0,
        'priority_category': 'IMMEDIATE',
        'expert_category': 'IMMEDIATE',
        'ml_category': 'IMMEDIATE',
        'proximity_to_hazard_km': 1.0,
        'elevation': 6.0,
        'slope_percentage': 0.4,
        'has_access_road': true,
        'path_status': 'DAMAGED',
        'geometry_wkt': 'POINT(86.39 20.20)',
        'assessment_timestamp': now,
        'model_version': 'bundled-demo-1.0',
      },
      {
        'habitation_id': 'OD_HAB_003',
        'state_code': 'OD',
        'district_name': 'Puri',
        'village_name': 'Astaranga',
        'latitude': 19.97,
        'longitude': 86.11,
        'total_population': 4410,
        'male_population': 2205,
        'female_population': 2205,
        'population_0_6': 544,
        'population_60_plus': 402,
        'literacy_rate': 74.0,
        'priority_score': 71.0,
        'priority_category': 'SHORT_TERM',
        'expert_category': 'SHORT_TERM',
        'ml_category': 'SHORT_TERM',
        'proximity_to_hazard_km': 2.2,
        'elevation': 8.0,
        'slope_percentage': 0.5,
        'has_access_road': true,
        'path_status': 'CLEAR',
        'geometry_wkt': 'POINT(86.11 19.97)',
        'assessment_timestamp': now,
        'model_version': 'bundled-demo-1.0',
      },
      {
        'habitation_id': 'OD_HAB_004',
        'state_code': 'OD',
        'district_name': 'Jagatsinghpur',
        'village_name': 'Kujanga',
        'latitude': 20.22,
        'longitude': 86.31,
        'total_population': 3100,
        'male_population': 1550,
        'female_population': 1550,
        'population_0_6': 390,
        'population_60_plus': 320,
        'literacy_rate': 77.0,
        'priority_score': 64.0,
        'priority_category': 'SHORT_TERM',
        'expert_category': 'SHORT_TERM',
        'ml_category': 'SHORT_TERM',
        'proximity_to_hazard_km': 3.4,
        'elevation': 10.0,
        'slope_percentage': 0.6,
        'has_access_road': true,
        'path_status': 'CLEAR',
        'geometry_wkt': 'POINT(86.31 20.22)',
        'assessment_timestamp': now,
        'model_version': 'bundled-demo-1.0',
      },
      {
        'habitation_id': 'OD_HAB_005',
        'state_code': 'OD',
        'district_name': 'Kendrapara',
        'village_name': 'Rajnagar',
        'latitude': 20.73,
        'longitude': 86.78,
        'total_population': 2860,
        'male_population': 1430,
        'female_population': 1430,
        'population_0_6': 318,
        'population_60_plus': 280,
        'literacy_rate': 75.0,
        'priority_score': 52.0,
        'priority_category': 'MEDIUM_TERM',
        'expert_category': 'MEDIUM_TERM',
        'ml_category': 'MEDIUM_TERM',
        'proximity_to_hazard_km': 6.2,
        'elevation': 13.0,
        'slope_percentage': 0.8,
        'has_access_road': true,
        'path_status': 'CLEAR',
        'geometry_wkt': 'POINT(86.78 20.73)',
        'assessment_timestamp': now,
        'model_version': 'bundled-demo-1.0',
      },
    ];

    final shelters = <Map<String, dynamic>>[
      {
        'shelter_id': 'OD_SH_001',
        'state_code': 'OD',
        'district_name': 'Kendrapara',
        'shelter_name': 'Rajnagar Cyclone Shelter',
        'shelter_type': 'GOVT_BUILDING',
        'latitude': 20.73,
        'longitude': 86.83,
        'total_capacity': 1200,
        'effective_capacity': 920,
        'available_capacity': 160,
        'utilization_percentage': 82.6,
        'current_population': 760,
        'water_available_liters': 16400,
        'food_available_kg': 920,
        'medical_kits_available': 16,
        'generator_fuel_liters': 150,
        'capacity_constraint': 'SPACE',
        'capacity_status': 'LIMITED',
        'is_in_safe_zone': true,
        'safety_buffer_km': 11.4,
        'overall_suitability': 'SUITABLE',
        'safety_score': 84.0,
        'has_generator': true,
        'has_medical_facility': true,
        'has_kitchen': true,
        'has_toilets': true,
        'access_road_status': 'CLEAR',
        'geometry_wkt': 'POINT(86.83 20.73)',
        'evaluation_timestamp': now,
        'model_version': 'bundled-demo-1.0',
      },
      {
        'shelter_id': 'OD_SH_002',
        'state_code': 'OD',
        'district_name': 'Jagatsinghpur',
        'shelter_name': 'Erasama College Relief Camp',
        'shelter_type': 'SCHOOL',
        'latitude': 20.23,
        'longitude': 86.40,
        'total_capacity': 900,
        'effective_capacity': 540,
        'available_capacity': 80,
        'utilization_percentage': 85.2,
        'current_population': 460,
        'water_available_liters': 9800,
        'food_available_kg': 610,
        'medical_kits_available': 10,
        'generator_fuel_liters': 60,
        'capacity_constraint': 'WATER',
        'capacity_status': 'LIMITED',
        'is_in_safe_zone': false,
        'safety_buffer_km': 4.8,
        'overall_suitability': 'MARGINAL',
        'safety_score': 46.0,
        'has_generator': false,
        'has_medical_facility': true,
        'has_kitchen': true,
        'has_toilets': true,
        'access_road_status': 'DAMAGED',
        'geometry_wkt': 'POINT(86.40 20.23)',
        'evaluation_timestamp': now,
        'model_version': 'bundled-demo-1.0',
      },
      {
        'shelter_id': 'OD_SH_003',
        'state_code': 'OD',
        'district_name': 'Puri',
        'shelter_name': 'Astaranga Block Shelter',
        'shelter_type': 'COMMUNITY_CENTER',
        'latitude': 19.98,
        'longitude': 86.14,
        'total_capacity': 780,
        'effective_capacity': 620,
        'available_capacity': 220,
        'utilization_percentage': 64.5,
        'current_population': 400,
        'water_available_liters': 24800,
        'food_available_kg': 1400,
        'medical_kits_available': 12,
        'generator_fuel_liters': 120,
        'capacity_constraint': 'NONE',
        'capacity_status': 'AVAILABLE',
        'is_in_safe_zone': true,
        'safety_buffer_km': 13.2,
        'overall_suitability': 'SUITABLE',
        'safety_score': 79.0,
        'has_generator': true,
        'has_medical_facility': true,
        'has_kitchen': true,
        'has_toilets': true,
        'access_road_status': 'CLEAR',
        'geometry_wkt': 'POINT(86.14 19.98)',
        'evaluation_timestamp': now,
        'model_version': 'bundled-demo-1.0',
      },
      {
        'shelter_id': 'OD_SH_004',
        'state_code': 'OD',
        'district_name': 'Jagatsinghpur',
        'shelter_name': 'Kujanga High School',
        'shelter_type': 'SCHOOL',
        'latitude': 20.25,
        'longitude': 86.32,
        'total_capacity': 640,
        'effective_capacity': 420,
        'available_capacity': 90,
        'utilization_percentage': 78.6,
        'current_population': 330,
        'water_available_liters': 6800,
        'food_available_kg': 510,
        'medical_kits_available': 6,
        'generator_fuel_liters': 40,
        'capacity_constraint': 'MEDICAL',
        'capacity_status': 'LIMITED',
        'is_in_safe_zone': true,
        'safety_buffer_km': 8.1,
        'overall_suitability': 'CONDITIONALLY_SUITABLE',
        'safety_score': 68.0,
        'has_generator': false,
        'has_medical_facility': false,
        'has_kitchen': true,
        'has_toilets': true,
        'access_road_status': 'CLEAR',
        'geometry_wkt': 'POINT(86.32 20.25)',
        'evaluation_timestamp': now,
        'model_version': 'bundled-demo-1.0',
      },
    ];

    return {
      'mode': 'DEMO_SCENARIO',
      'generated_at': now,
      'bbox': {'south': south, 'west': west, 'north': north, 'east': east},
      'scenario': {
        'scenario_id': 'bundled_odisha_cyclone',
        'name': 'Bundled Cyclone Scenario - Odisha Coast',
        'description': 'Bundled offline scenario used when the backend is unreachable on the device.',
        'geography': 'Odisha coastal districts',
        'hazard_mix': ['COASTAL_EROSION', 'FLOOD', 'CYCLONE'],
      },
      'data_sources': {
        'mode': 'Bundled mobile demo fallback',
        'scenario_dataset': 'Bundled Cyclone Scenario - Odisha Coast',
        'backend_status': 'Unavailable from device; using on-device scenario fallback',
      },
      'alert': {
        'active': true,
        'headline': 'Bundled cyclone scenario active for offline mobile demo',
        'detail': 'The phone could not reach the local backend, so the app loaded a bundled deterministic scenario to keep the demo operational.',
        'worst_lat': 20.34,
        'worst_lon': 86.62,
        'worst_risk': 92.0,
      },
      'summary': {
        'red_zone_count': redZones.length,
        'habitation_count': habitations.length,
        'immediate_count': habitations.where((h) => h['priority_category'] == 'IMMEDIATE').length,
        'short_term_count': habitations.where((h) => h['priority_category'] == 'SHORT_TERM').length,
        'medium_term_count': habitations.where((h) => h['priority_category'] == 'MEDIUM_TERM').length,
        'shelter_count': shelters.length,
        'safe_shelter_count': shelters.where((s) => s['is_in_safe_zone'] == true).length,
        'available_beds': shelters.where((s) => s['is_in_safe_zone'] == true).fold<int>(0, (sum, s) => sum + (s['available_capacity'] as int)),
        'population_immediate': habitations.where((h) => h['priority_category'] == 'IMMEDIATE').fold<int>(0, (sum, h) => sum + (h['total_population'] as int)),
      },
      'red_zones': redZones,
      'grid_cells': redZones
          .map((z) => {
                'latitude': z['latitude'],
                'longitude': z['longitude'],
                'risk_score': z['risk_score'],
                'is_red_zone': z['is_red_zone'],
                'hazard_type': z['hazard_type'],
                'precipitation_24h_mm': null,
                'elevation': null,
                'slope_percentage': null,
              })
          .toList(),
      'habitations': habitations,
      'shelters': shelters,
      'cache_hit': false,
    };
  }

  static Map<String, dynamic> inspect({
    required double latitude,
    required double longitude,
  }) {
    final data = snapshot(south: 6.5, west: 68.0, north: 37.1, east: 97.4);
    final zones = (data['red_zones'] as List).cast<Map<String, dynamic>>();
    final shelters = (data['shelters'] as List).cast<Map<String, dynamic>>();
    final nearestZone = zones.reduce((a, b) => _distance(latitude, longitude, a['latitude'] as double, a['longitude'] as double) < _distance(latitude, longitude, b['latitude'] as double, b['longitude'] as double) ? a : b);
    final nearestZoneKm = _distance(latitude, longitude, nearestZone['latitude'] as double, nearestZone['longitude'] as double);
    final nearestShelter = shelters.reduce((a, b) => _distance(latitude, longitude, a['latitude'] as double, a['longitude'] as double) < _distance(latitude, longitude, b['latitude'] as double, b['longitude'] as double) ? a : b);
    final nearestShelterKm = _distance(latitude, longitude, nearestShelter['latitude'] as double, nearestShelter['longitude'] as double);
    final decay = math.max(0.25, 1.0 - math.min(nearestZoneKm, 25.0) / 35.0);
    final riskScore = double.parse(((nearestZone['risk_score'] as num) * decay).toStringAsFixed(2));
    final riskLevel = riskScore >= 85 ? 'CRITICAL' : riskScore >= 65 ? 'HIGH' : riskScore >= 40 ? 'MEDIUM' : 'LOW';
    return {
      'mode': 'DEMO_SCENARIO',
      'scenario': data['scenario'],
      'latitude': latitude,
      'longitude': longitude,
      'is_within_india': true,
      'risk_score': riskScore,
      'is_red_zone': riskScore >= 55,
      'risk_level': riskLevel,
      'hazard_type': nearestZone['hazard_type'],
      'urgency': riskScore >= 75 ? 'IMMEDIATE' : riskScore >= 50 ? 'SHORT_TERM' : 'MEDIUM_TERM',
      'elevation': null,
      'slope_percentage': null,
      'precipitation_24h_mm': null,
      'precipitation_72h_mm': null,
      'soil_moisture_index': null,
      'temperature_celsius': null,
      'wind_speed_kmh': null,
      'humidity': null,
      'nearest_shelter': nearestShelter,
      'nearest_shelter_km': double.parse(nearestShelterKm.toStringAsFixed(2)),
      'red_zone_count_nearby': zones.where((z) => _distance(latitude, longitude, z['latitude'] as double, z['longitude'] as double) <= 20.0).length,
      'nearest_red_zone_distance_km': double.parse(nearestZoneKm.toStringAsFixed(2)),
      'model_version': 'bundled-demo-1.0',
      'inspected_at': DateTime.now().toUtc().toIso8601String(),
      'data_sources': data['data_sources'],
    };
  }

  static Map<String, dynamic> evaluateCandidateSite({
    required String siteName,
    required String districtName,
    required String stateCode,
    required double latitude,
    required double longitude,
    required double hectares,
    required double roadDistanceKm,
    required bool waterSupply,
    required bool sanitationFacilities,
    required bool electricity,
    required String medicalFacilityDepth,
  }) {
    final inspected = inspect(latitude: latitude, longitude: longitude);
    final riskScore = (inspected['risk_score'] as num).toDouble();
    final bufferKm = (inspected['nearest_red_zone_distance_km'] as num?)?.toDouble() ?? 12.0;
    final elevation = 14.0 + ((latitude * 10).round() % 12);
    final slope = 1.5 + ((longitude * 10).round() % 8) / 2;
    final plannedCapacity = math.max(50, (hectares * 1250).round());
    final physicalBeds = math.max(50, (plannedCapacity * 0.82).round());
    final effectiveCapacity = math.max(30, plannedCapacity - (riskScore / 2).round());
    final availableCapacity = effectiveCapacity;
    final safetyScore = double.parse((math.max(0, math.min(100, 100 - riskScore * 0.55 + math.min(25, bufferKm * 4)))).toStringAsFixed(2));
    final overallScore = double.parse((math.max(0, math.min(100, safetyScore * 0.45 + (electricity ? 10 : 0) + (waterSupply ? 10 : 0) + (sanitationFacilities ? 10 : 0) + (roadDistanceKm <= 1 ? 18 : 8) + (plannedCapacity / 200)))).toStringAsFixed(2));
    final suitability = overallScore >= 78
        ? 'SUITABLE'
        : overallScore >= 60
            ? 'CONDITIONALLY_SUITABLE'
            : 'UNSUITABLE';
    return {
      'candidate_site_id': 'LOCAL_${latitude.toStringAsFixed(3).replaceAll('.', '_')}_${longitude.toStringAsFixed(3).replaceAll('.', '_')}',
      'site_name': siteName,
      'district_name': districtName,
      'state_code': stateCode,
      'latitude': latitude,
      'longitude': longitude,
      'hectares': hectares,
      'road_distance_km': roadDistanceKm,
      'nearest_red_zone_distance_km': double.parse(bufferKm.toStringAsFixed(2)),
      'terrain': {
        'elevation_m': elevation,
        'slope_percentage': double.parse(slope.toStringAsFixed(2)),
      },
      'hazard_context': {
        'risk_score': riskScore,
        'risk_level': inspected['risk_level'],
        'hazard_type': inspected['hazard_type'],
        'precipitation_24h_mm': null,
        'precipitation_72h_mm': null,
        'soil_moisture_index': null,
      },
      'capacity': {
        'planned_population_capacity': plannedCapacity,
        'physical_beds': physicalBeds,
        'water_available_liters': waterSupply ? plannedCapacity * 14 : plannedCapacity * 5,
        'food_available_kg': plannedCapacity * 8,
      },
      'capacity_evaluation': {
        'effective_capacity': effectiveCapacity,
        'available_capacity': availableCapacity,
        'utilization_percentage': 0.0,
        'capacity_constraint': waterSupply ? 'NONE' : 'WATER',
        'capacity_status': availableCapacity >= 500 ? 'AVAILABLE' : 'LIMITED',
      },
      'safety_evaluation': {
        'safety_check_passed': suitability != 'UNSUITABLE',
        'intersects_red_zone': bufferKm < 5,
      },
      'safety_score': safetyScore,
      'terrain_score': suitability == 'SUITABLE' ? 82.0 : suitability == 'CONDITIONALLY_SUITABLE' ? 63.0 : 39.0,
      'overall_score': overallScore,
      'overall_suitability': suitability,
      'recommendation': suitability == 'SUITABLE' ? 'DESIGNATE_FOR_RELOCATION' : suitability == 'CONDITIONALLY_SUITABLE' ? 'REVIEW_WITH_MITIGATION' : 'REJECT_SITE',
      'geometry_wkt': 'POINT($longitude $latitude)',
      'evaluated_at': DateTime.now().toUtc().toIso8601String(),
      'data_sources': {
        'mode': 'Bundled mobile demo fallback',
      },
    };
  }

  static double _distance(double lat1, double lon1, double lat2, double lon2) {
    const r = 6371.0;
    final dLat = _degToRad(lat2 - lat1);
    final dLon = _degToRad(lon2 - lon1);
    final a = math.sin(dLat / 2) * math.sin(dLat / 2) + math.cos(_degToRad(lat1)) * math.cos(_degToRad(lat2)) * math.sin(dLon / 2) * math.sin(dLon / 2);
    final c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a));
    return r * c;
  }

  static double _degToRad(double deg) => deg * math.pi / 180.0;
}
