"""Curated static scenarios for SIH prototype demonstrations."""

from __future__ import annotations

from collections import Counter
from copy import deepcopy
from datetime import datetime, timezone
from math import atan2, cos, radians, sin, sqrt
from typing import Any, Dict, List, Optional, Tuple

INDIA_BBOX = (6.5, 68.0, 37.1, 97.4)

_ACTIVE_SCENARIO_ID = "odisha_cyclone"


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _haversine_km(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    r = 6371.0
    p1, p2 = radians(lat1), radians(lat2)
    dphi = radians(lat2 - lat1)
    dl = radians(lon2 - lon1)
    a = sin(dphi / 2) ** 2 + cos(p1) * cos(p2) * sin(dl / 2) ** 2
    return 2 * r * atan2(sqrt(a), sqrt(1 - a))


SCENARIOS: Dict[str, Dict[str, Any]] = {
    "odisha_cyclone": {
        "scenario_id": "odisha_cyclone",
        "name": "Cyclone Landfall Stress Test - Odisha Coast",
        "description": "Cyclone-driven coastal flooding and evacuation pressure across Kendrapara, Jagatsinghpur, and Puri.",
        "geography": "Odisha coastal districts",
        "hazard_mix": ["COASTAL_EROSION", "FLOOD", "CYCLONE"],
        "bbox": {"south": 19.55, "west": 85.30, "north": 20.85, "east": 87.25},
        "alert": {
            "headline": "Cyclone surge and coastal flood scenario active along the Odisha coast",
            "detail": "Preloaded landfall scenario highlights exposed coastal habitations, unsafe shelters, and candidate relocation shortfalls.",
        },
        "red_zones": [
            {
                "zone_id": "ODCY_RZ_01",
                "grid_id": "ODCY_GRID_01",
                "latitude": 20.34,
                "longitude": 86.62,
                "risk_score": 92.0,
                "is_red_zone": True,
                "risk_level": "CRITICAL",
                "hazard_type": "COASTAL_EROSION",
                "geometry_wkt": "POLYGON((86.46 20.18, 86.78 20.18, 86.86 20.36, 86.76 20.52, 86.42 20.48, 86.46 20.18))",
                "prediction_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
                "time_horizon": "IMMEDIATE",
                "grid_count": 9,
                "area_sq_km": 132.4,
            },
            {
                "zone_id": "ODCY_RZ_02",
                "grid_id": "ODCY_GRID_02",
                "latitude": 20.18,
                "longitude": 86.21,
                "risk_score": 84.0,
                "is_red_zone": True,
                "risk_level": "CRITICAL",
                "hazard_type": "FLOOD",
                "geometry_wkt": "POLYGON((86.02 20.00, 86.34 19.98, 86.42 20.14, 86.28 20.31, 86.00 20.26, 86.02 20.00))",
                "prediction_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
                "time_horizon": "IMMEDIATE",
                "grid_count": 7,
                "area_sq_km": 104.2,
            },
            {
                "zone_id": "ODCY_RZ_03",
                "grid_id": "ODCY_GRID_03",
                "latitude": 19.93,
                "longitude": 85.95,
                "risk_score": 68.0,
                "is_red_zone": True,
                "risk_level": "HIGH",
                "hazard_type": "FLOOD",
                "geometry_wkt": "POLYGON((85.76 19.80, 86.08 19.78, 86.16 19.94, 86.00 20.09, 85.74 20.00, 85.76 19.80))",
                "prediction_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
                "time_horizon": "SHORT_TERM",
                "grid_count": 5,
                "area_sq_km": 82.5,
            },
        ],
        "habitations": [
            {
                "habitation_id": "OD_HAB_001",
                "state_code": "OD",
                "district_name": "Kendrapara",
                "village_name": "Satabhaya",
                "latitude": 20.61,
                "longitude": 86.89,
                "total_population": 3620,
                "male_population": 1810,
                "female_population": 1810,
                "population_0_6": 470,
                "population_60_plus": 392,
                "literacy_rate": 69.0,
                "priority_score": 91.0,
                "priority_category": "IMMEDIATE",
                "expert_category": "IMMEDIATE",
                "ml_category": "IMMEDIATE",
                "proximity_to_hazard_km": 0.6,
                "elevation": 4.0,
                "slope_percentage": 0.3,
                "has_access_road": True,
                "path_status": "DAMAGED",
                "geometry_wkt": "POINT(86.89 20.61)",
                "assessment_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
                "field_survey_notes": "Coastal erosion pressure and repeated saline inundation.",
            },
            {
                "habitation_id": "OD_HAB_002",
                "state_code": "OD",
                "district_name": "Jagatsinghpur",
                "village_name": "Erasama",
                "latitude": 20.20,
                "longitude": 86.39,
                "total_population": 4980,
                "male_population": 2490,
                "female_population": 2490,
                "population_0_6": 610,
                "population_60_plus": 510,
                "literacy_rate": 72.0,
                "priority_score": 83.0,
                "priority_category": "IMMEDIATE",
                "expert_category": "IMMEDIATE",
                "ml_category": "IMMEDIATE",
                "proximity_to_hazard_km": 1.0,
                "elevation": 6.0,
                "slope_percentage": 0.4,
                "has_access_road": True,
                "path_status": "DAMAGED",
                "geometry_wkt": "POINT(86.39 20.20)",
                "assessment_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
            },
            {
                "habitation_id": "OD_HAB_003",
                "state_code": "OD",
                "district_name": "Puri",
                "village_name": "Astaranga",
                "latitude": 19.97,
                "longitude": 86.11,
                "total_population": 4410,
                "male_population": 2205,
                "female_population": 2205,
                "population_0_6": 544,
                "population_60_plus": 402,
                "literacy_rate": 74.0,
                "priority_score": 71.0,
                "priority_category": "SHORT_TERM",
                "expert_category": "SHORT_TERM",
                "ml_category": "SHORT_TERM",
                "proximity_to_hazard_km": 2.2,
                "elevation": 8.0,
                "slope_percentage": 0.5,
                "has_access_road": True,
                "path_status": "CLEAR",
                "geometry_wkt": "POINT(86.11 19.97)",
                "assessment_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
            },
            {
                "habitation_id": "OD_HAB_004",
                "state_code": "OD",
                "district_name": "Jagatsinghpur",
                "village_name": "Kujanga",
                "latitude": 20.22,
                "longitude": 86.31,
                "total_population": 3100,
                "male_population": 1550,
                "female_population": 1550,
                "population_0_6": 390,
                "population_60_plus": 320,
                "literacy_rate": 77.0,
                "priority_score": 64.0,
                "priority_category": "SHORT_TERM",
                "expert_category": "SHORT_TERM",
                "ml_category": "SHORT_TERM",
                "proximity_to_hazard_km": 3.4,
                "elevation": 10.0,
                "slope_percentage": 0.6,
                "has_access_road": True,
                "path_status": "CLEAR",
                "geometry_wkt": "POINT(86.31 20.22)",
                "assessment_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
            },
            {
                "habitation_id": "OD_HAB_005",
                "state_code": "OD",
                "district_name": "Kendrapara",
                "village_name": "Rajnagar",
                "latitude": 20.73,
                "longitude": 86.78,
                "total_population": 2860,
                "male_population": 1430,
                "female_population": 1430,
                "population_0_6": 318,
                "population_60_plus": 280,
                "literacy_rate": 75.0,
                "priority_score": 52.0,
                "priority_category": "MEDIUM_TERM",
                "expert_category": "MEDIUM_TERM",
                "ml_category": "MEDIUM_TERM",
                "proximity_to_hazard_km": 6.2,
                "elevation": 13.0,
                "slope_percentage": 0.8,
                "has_access_road": True,
                "path_status": "CLEAR",
                "geometry_wkt": "POINT(86.78 20.73)",
                "assessment_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
            },
        ],
        "shelters": [
            {
                "shelter_id": "OD_SH_001",
                "state_code": "OD",
                "district_name": "Kendrapara",
                "shelter_name": "Rajnagar Cyclone Shelter",
                "shelter_type": "GOVT_BUILDING",
                "latitude": 20.73,
                "longitude": 86.83,
                "total_capacity": 1200,
                "effective_capacity": 920,
                "available_capacity": 160,
                "utilization_percentage": 82.6,
                "current_population": 760,
                "water_available_liters": 16400,
                "food_available_kg": 920,
                "medical_kits_available": 16,
                "generator_fuel_liters": 150,
                "capacity_constraint": "SPACE",
                "capacity_status": "LIMITED",
                "is_in_safe_zone": True,
                "safety_buffer_km": 11.4,
                "overall_suitability": "SUITABLE",
                "safety_score": 84.0,
                "has_generator": True,
                "has_medical_facility": True,
                "has_kitchen": True,
                "has_toilets": True,
                "access_road_status": "CLEAR",
                "geometry_wkt": "POINT(86.83 20.73)",
                "evaluation_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
            },
            {
                "shelter_id": "OD_SH_002",
                "state_code": "OD",
                "district_name": "Jagatsinghpur",
                "shelter_name": "Erasama College Relief Camp",
                "shelter_type": "SCHOOL",
                "latitude": 20.23,
                "longitude": 86.40,
                "total_capacity": 900,
                "effective_capacity": 540,
                "available_capacity": 80,
                "utilization_percentage": 85.2,
                "current_population": 460,
                "water_available_liters": 9800,
                "food_available_kg": 610,
                "medical_kits_available": 10,
                "generator_fuel_liters": 60,
                "capacity_constraint": "WATER",
                "capacity_status": "LIMITED",
                "is_in_safe_zone": False,
                "safety_buffer_km": 4.8,
                "overall_suitability": "MARGINAL",
                "safety_score": 46.0,
                "has_generator": False,
                "has_medical_facility": True,
                "has_kitchen": True,
                "has_toilets": True,
                "access_road_status": "DAMAGED",
                "geometry_wkt": "POINT(86.40 20.23)",
                "evaluation_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
            },
            {
                "shelter_id": "OD_SH_003",
                "state_code": "OD",
                "district_name": "Puri",
                "shelter_name": "Astaranga Block Shelter",
                "shelter_type": "COMMUNITY_CENTER",
                "latitude": 19.98,
                "longitude": 86.14,
                "total_capacity": 780,
                "effective_capacity": 620,
                "available_capacity": 220,
                "utilization_percentage": 64.5,
                "current_population": 400,
                "water_available_liters": 24800,
                "food_available_kg": 1400,
                "medical_kits_available": 12,
                "generator_fuel_liters": 120,
                "capacity_constraint": "NONE",
                "capacity_status": "AVAILABLE",
                "is_in_safe_zone": True,
                "safety_buffer_km": 13.2,
                "overall_suitability": "SUITABLE",
                "safety_score": 79.0,
                "has_generator": True,
                "has_medical_facility": True,
                "has_kitchen": True,
                "has_toilets": True,
                "access_road_status": "CLEAR",
                "geometry_wkt": "POINT(86.14 19.98)",
                "evaluation_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
            },
            {
                "shelter_id": "OD_SH_004",
                "state_code": "OD",
                "district_name": "Jagatsinghpur",
                "shelter_name": "Kujanga High School",
                "shelter_type": "SCHOOL",
                "latitude": 20.25,
                "longitude": 86.32,
                "total_capacity": 640,
                "effective_capacity": 420,
                "available_capacity": 90,
                "utilization_percentage": 78.6,
                "current_population": 330,
                "water_available_liters": 6800,
                "food_available_kg": 510,
                "medical_kits_available": 6,
                "generator_fuel_liters": 40,
                "capacity_constraint": "MEDICAL",
                "capacity_status": "LIMITED",
                "is_in_safe_zone": True,
                "safety_buffer_km": 8.1,
                "overall_suitability": "CONDITIONALLY_SUITABLE",
                "safety_score": 68.0,
                "has_generator": False,
                "has_medical_facility": False,
                "has_kitchen": True,
                "has_toilets": True,
                "access_road_status": "CLEAR",
                "geometry_wkt": "POINT(86.32 20.25)",
                "evaluation_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
            },
        ],
    },
    "assam_flood": {
        "scenario_id": "assam_flood",
        "name": "Brahmaputra Flood Escalation - Assam",
        "description": "Riverine inundation across Dhemaji, Lakhimpur, and Majuli with shelter bottlenecks and cut road access.",
        "geography": "Upper Assam floodplain districts",
        "hazard_mix": ["FLOOD"],
        "bbox": {"south": 26.55, "west": 93.55, "north": 27.95, "east": 95.25},
        "alert": {
            "headline": "Brahmaputra flood scenario active across upper Assam",
            "detail": "Preloaded basin overflow scenario emphasizes cut-off embankment settlements and district-level evacuation capacity shortfalls.",
        },
        "red_zones": [
            {
                "zone_id": "ASF_RZ_01",
                "grid_id": "ASF_GRID_01",
                "latitude": 27.47,
                "longitude": 94.61,
                "risk_score": 89.0,
                "is_red_zone": True,
                "risk_level": "CRITICAL",
                "hazard_type": "FLOOD",
                "geometry_wkt": "POLYGON((94.33 27.28, 94.82 27.26, 94.92 27.48, 94.73 27.66, 94.30 27.58, 94.33 27.28))",
                "prediction_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
                "time_horizon": "IMMEDIATE",
                "grid_count": 10,
                "area_sq_km": 148.1,
            },
            {
                "zone_id": "ASF_RZ_02",
                "grid_id": "ASF_GRID_02",
                "latitude": 27.12,
                "longitude": 94.19,
                "risk_score": 78.0,
                "is_red_zone": True,
                "risk_level": "CRITICAL",
                "hazard_type": "FLOOD",
                "geometry_wkt": "POLYGON((93.91 26.95, 94.37 26.92, 94.49 27.14, 94.28 27.34, 93.88 27.28, 93.91 26.95))",
                "prediction_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
                "time_horizon": "IMMEDIATE",
                "grid_count": 8,
                "area_sq_km": 126.2,
            },
            {
                "zone_id": "ASF_RZ_03",
                "grid_id": "ASF_GRID_03",
                "latitude": 26.92,
                "longitude": 94.03,
                "risk_score": 64.0,
                "is_red_zone": True,
                "risk_level": "HIGH",
                "hazard_type": "FLOOD",
                "geometry_wkt": "POLYGON((93.82 26.77, 94.19 26.75, 94.25 26.92, 94.08 27.08, 93.79 27.02, 93.82 26.77))",
                "prediction_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
                "time_horizon": "SHORT_TERM",
                "grid_count": 5,
                "area_sq_km": 89.0,
            },
        ],
        "habitations": [
            {
                "habitation_id": "AS_HAB_001",
                "state_code": "AS",
                "district_name": "Dhemaji",
                "village_name": "Jonai",
                "latitude": 27.56,
                "longitude": 94.77,
                "total_population": 5240,
                "male_population": 2620,
                "female_population": 2620,
                "population_0_6": 690,
                "population_60_plus": 430,
                "literacy_rate": 71.0,
                "priority_score": 88.0,
                "priority_category": "IMMEDIATE",
                "expert_category": "IMMEDIATE",
                "ml_category": "IMMEDIATE",
                "proximity_to_hazard_km": 0.7,
                "elevation": 88.0,
                "slope_percentage": 0.4,
                "has_access_road": True,
                "path_status": "BLOCKED",
                "geometry_wkt": "POINT(94.77 27.56)",
                "assessment_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
            },
            {
                "habitation_id": "AS_HAB_002",
                "state_code": "AS",
                "district_name": "Lakhimpur",
                "village_name": "Dhakuakhana",
                "latitude": 27.24,
                "longitude": 94.11,
                "total_population": 4680,
                "male_population": 2340,
                "female_population": 2340,
                "population_0_6": 602,
                "population_60_plus": 410,
                "literacy_rate": 73.0,
                "priority_score": 80.0,
                "priority_category": "IMMEDIATE",
                "expert_category": "IMMEDIATE",
                "ml_category": "IMMEDIATE",
                "proximity_to_hazard_km": 1.1,
                "elevation": 94.0,
                "slope_percentage": 0.5,
                "has_access_road": True,
                "path_status": "DAMAGED",
                "geometry_wkt": "POINT(94.11 27.24)",
                "assessment_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
            },
            {
                "habitation_id": "AS_HAB_003",
                "state_code": "AS",
                "district_name": "Majuli",
                "village_name": "Kamalabari",
                "latitude": 26.95,
                "longitude": 94.18,
                "total_population": 3560,
                "male_population": 1780,
                "female_population": 1780,
                "population_0_6": 420,
                "population_60_plus": 330,
                "literacy_rate": 76.0,
                "priority_score": 69.0,
                "priority_category": "SHORT_TERM",
                "expert_category": "SHORT_TERM",
                "ml_category": "SHORT_TERM",
                "proximity_to_hazard_km": 2.3,
                "elevation": 87.0,
                "slope_percentage": 0.4,
                "has_access_road": True,
                "path_status": "DAMAGED",
                "geometry_wkt": "POINT(94.18 26.95)",
                "assessment_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
            },
            {
                "habitation_id": "AS_HAB_004",
                "state_code": "AS",
                "district_name": "Dhemaji",
                "village_name": "Silapathar",
                "latitude": 27.59,
                "longitude": 94.72,
                "total_population": 2910,
                "male_population": 1455,
                "female_population": 1455,
                "population_0_6": 320,
                "population_60_plus": 270,
                "literacy_rate": 79.0,
                "priority_score": 57.0,
                "priority_category": "MEDIUM_TERM",
                "expert_category": "MEDIUM_TERM",
                "ml_category": "MEDIUM_TERM",
                "proximity_to_hazard_km": 5.2,
                "elevation": 96.0,
                "slope_percentage": 0.6,
                "has_access_road": True,
                "path_status": "CLEAR",
                "geometry_wkt": "POINT(94.72 27.59)",
                "assessment_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
            },
        ],
        "shelters": [
            {
                "shelter_id": "AS_SH_001",
                "state_code": "AS",
                "district_name": "Dhemaji",
                "shelter_name": "Jonai College Shelter",
                "shelter_type": "SCHOOL",
                "latitude": 27.57,
                "longitude": 94.78,
                "total_capacity": 980,
                "effective_capacity": 630,
                "available_capacity": 40,
                "utilization_percentage": 93.7,
                "current_population": 590,
                "water_available_liters": 7100,
                "food_available_kg": 480,
                "medical_kits_available": 7,
                "generator_fuel_liters": 35,
                "capacity_constraint": "WATER",
                "capacity_status": "CRITICAL",
                "is_in_safe_zone": False,
                "safety_buffer_km": 3.4,
                "overall_suitability": "UNSUITABLE",
                "safety_score": 38.0,
                "has_generator": False,
                "has_medical_facility": False,
                "has_kitchen": True,
                "has_toilets": True,
                "access_road_status": "DAMAGED",
                "geometry_wkt": "POINT(94.78 27.57)",
                "evaluation_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
            },
            {
                "shelter_id": "AS_SH_002",
                "state_code": "AS",
                "district_name": "Lakhimpur",
                "shelter_name": "Dhakuakhana Block Relief Centre",
                "shelter_type": "GOVT_BUILDING",
                "latitude": 27.23,
                "longitude": 94.12,
                "total_capacity": 1100,
                "effective_capacity": 880,
                "available_capacity": 210,
                "utilization_percentage": 76.1,
                "current_population": 670,
                "water_available_liters": 26500,
                "food_available_kg": 1540,
                "medical_kits_available": 15,
                "generator_fuel_liters": 140,
                "capacity_constraint": "NONE",
                "capacity_status": "AVAILABLE",
                "is_in_safe_zone": True,
                "safety_buffer_km": 14.8,
                "overall_suitability": "SUITABLE",
                "safety_score": 82.0,
                "has_generator": True,
                "has_medical_facility": True,
                "has_kitchen": True,
                "has_toilets": True,
                "access_road_status": "CLEAR",
                "geometry_wkt": "POINT(94.12 27.23)",
                "evaluation_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
            },
            {
                "shelter_id": "AS_SH_003",
                "state_code": "AS",
                "district_name": "Majuli",
                "shelter_name": "Kamalabari Cultural Hall",
                "shelter_type": "COMMUNITY_CENTER",
                "latitude": 26.96,
                "longitude": 94.19,
                "total_capacity": 720,
                "effective_capacity": 470,
                "available_capacity": 90,
                "utilization_percentage": 80.9,
                "current_population": 380,
                "water_available_liters": 9900,
                "food_available_kg": 620,
                "medical_kits_available": 8,
                "generator_fuel_liters": 70,
                "capacity_constraint": "SPACE",
                "capacity_status": "LIMITED",
                "is_in_safe_zone": True,
                "safety_buffer_km": 9.3,
                "overall_suitability": "CONDITIONALLY_SUITABLE",
                "safety_score": 66.0,
                "has_generator": True,
                "has_medical_facility": False,
                "has_kitchen": True,
                "has_toilets": True,
                "access_road_status": "CLEAR",
                "geometry_wkt": "POINT(94.19 26.96)",
                "evaluation_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
            },
        ],
    },
    "uttarakhand_landslide": {
        "scenario_id": "uttarakhand_landslide",
        "name": "Cloudburst and Landslide Cascade - Uttarakhand",
        "description": "Mountain road cut-offs and slope-failure relocation planning around Rudraprayag, Chamoli, and Uttarkashi.",
        "geography": "Central Himalayan districts",
        "hazard_mix": ["LANDSLIDE", "CLOUDBURST"],
        "bbox": {"south": 30.15, "west": 78.05, "north": 31.55, "east": 79.45},
        "alert": {
            "headline": "Cloudburst-induced landslide scenario active in central Uttarakhand",
            "detail": "Preloaded mountain-hazard scenario emphasizes slope instability, route damage, and constrained shelter access windows.",
        },
        "red_zones": [
            {
                "zone_id": "UKL_RZ_01",
                "grid_id": "UKL_GRID_01",
                "latitude": 30.54,
                "longitude": 79.07,
                "risk_score": 94.0,
                "is_red_zone": True,
                "risk_level": "CRITICAL",
                "hazard_type": "LANDSLIDE",
                "geometry_wkt": "POLYGON((78.95 30.40, 79.17 30.39, 79.21 30.56, 79.08 30.67, 78.91 30.61, 78.95 30.40))",
                "prediction_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
                "time_horizon": "IMMEDIATE",
                "grid_count": 6,
                "area_sq_km": 61.2,
            },
            {
                "zone_id": "UKL_RZ_02",
                "grid_id": "UKL_GRID_02",
                "latitude": 30.74,
                "longitude": 78.52,
                "risk_score": 86.0,
                "is_red_zone": True,
                "risk_level": "CRITICAL",
                "hazard_type": "CLOUDBURST",
                "geometry_wkt": "POLYGON((78.37 30.60, 78.65 30.58, 78.70 30.74, 78.53 30.88, 78.33 30.81, 78.37 30.60))",
                "prediction_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
                "time_horizon": "IMMEDIATE",
                "grid_count": 5,
                "area_sq_km": 54.9,
            },
            {
                "zone_id": "UKL_RZ_03",
                "grid_id": "UKL_GRID_03",
                "latitude": 31.09,
                "longitude": 78.43,
                "risk_score": 71.0,
                "is_red_zone": True,
                "risk_level": "HIGH",
                "hazard_type": "LANDSLIDE",
                "geometry_wkt": "POLYGON((78.29 30.96, 78.54 30.94, 78.59 31.12, 78.41 31.24, 78.24 31.17, 78.29 30.96))",
                "prediction_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
                "time_horizon": "SHORT_TERM",
                "grid_count": 5,
                "area_sq_km": 48.6,
            },
        ],
        "habitations": [
            {
                "habitation_id": "UK_HAB_001",
                "state_code": "UK",
                "district_name": "Rudraprayag",
                "village_name": "Ukhimath",
                "latitude": 30.53,
                "longitude": 79.06,
                "total_population": 2140,
                "male_population": 1070,
                "female_population": 1070,
                "population_0_6": 220,
                "population_60_plus": 240,
                "literacy_rate": 84.0,
                "priority_score": 90.0,
                "priority_category": "IMMEDIATE",
                "expert_category": "IMMEDIATE",
                "ml_category": "IMMEDIATE",
                "proximity_to_hazard_km": 0.9,
                "elevation": 1310.0,
                "slope_percentage": 23.0,
                "has_access_road": True,
                "path_status": "BLOCKED",
                "geometry_wkt": "POINT(79.06 30.53)",
                "assessment_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
            },
            {
                "habitation_id": "UK_HAB_002",
                "state_code": "UK",
                "district_name": "Chamoli",
                "village_name": "Joshimath Fringe",
                "latitude": 30.56,
                "longitude": 79.56,
                "total_population": 3380,
                "male_population": 1690,
                "female_population": 1690,
                "population_0_6": 360,
                "population_60_plus": 310,
                "literacy_rate": 86.0,
                "priority_score": 79.0,
                "priority_category": "IMMEDIATE",
                "expert_category": "IMMEDIATE",
                "ml_category": "IMMEDIATE",
                "proximity_to_hazard_km": 1.4,
                "elevation": 1820.0,
                "slope_percentage": 19.0,
                "has_access_road": True,
                "path_status": "DAMAGED",
                "geometry_wkt": "POINT(79.56 30.56)",
                "assessment_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
            },
            {
                "habitation_id": "UK_HAB_003",
                "state_code": "UK",
                "district_name": "Uttarkashi",
                "village_name": "Barkot Corridor",
                "latitude": 30.81,
                "longitude": 78.20,
                "total_population": 2620,
                "male_population": 1310,
                "female_population": 1310,
                "population_0_6": 250,
                "population_60_plus": 250,
                "literacy_rate": 82.0,
                "priority_score": 67.0,
                "priority_category": "SHORT_TERM",
                "expert_category": "SHORT_TERM",
                "ml_category": "SHORT_TERM",
                "proximity_to_hazard_km": 2.8,
                "elevation": 1220.0,
                "slope_percentage": 16.0,
                "has_access_road": True,
                "path_status": "DAMAGED",
                "geometry_wkt": "POINT(78.20 30.81)",
                "assessment_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
            },
            {
                "habitation_id": "UK_HAB_004",
                "state_code": "UK",
                "district_name": "Rudraprayag",
                "village_name": "Agastyamuni",
                "latitude": 30.39,
                "longitude": 79.02,
                "total_population": 2790,
                "male_population": 1395,
                "female_population": 1395,
                "population_0_6": 285,
                "population_60_plus": 255,
                "literacy_rate": 85.0,
                "priority_score": 54.0,
                "priority_category": "MEDIUM_TERM",
                "expert_category": "MEDIUM_TERM",
                "ml_category": "MEDIUM_TERM",
                "proximity_to_hazard_km": 6.0,
                "elevation": 960.0,
                "slope_percentage": 9.0,
                "has_access_road": True,
                "path_status": "CLEAR",
                "geometry_wkt": "POINT(79.02 30.39)",
                "assessment_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
            },
        ],
        "shelters": [
            {
                "shelter_id": "UK_SH_001",
                "state_code": "UK",
                "district_name": "Rudraprayag",
                "shelter_name": "Ukhimath Inter College Camp",
                "shelter_type": "SCHOOL",
                "latitude": 30.54,
                "longitude": 79.09,
                "total_capacity": 540,
                "effective_capacity": 360,
                "available_capacity": 40,
                "utilization_percentage": 88.9,
                "current_population": 320,
                "water_available_liters": 5200,
                "food_available_kg": 410,
                "medical_kits_available": 7,
                "generator_fuel_liters": 60,
                "capacity_constraint": "SPACE",
                "capacity_status": "CRITICAL",
                "is_in_safe_zone": False,
                "safety_buffer_km": 2.9,
                "overall_suitability": "UNSUITABLE",
                "safety_score": 32.0,
                "has_generator": True,
                "has_medical_facility": False,
                "has_kitchen": True,
                "has_toilets": True,
                "access_road_status": "DAMAGED",
                "geometry_wkt": "POINT(79.09 30.54)",
                "evaluation_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
            },
            {
                "shelter_id": "UK_SH_002",
                "state_code": "UK",
                "district_name": "Chamoli",
                "shelter_name": "Joshimath Sports Hall",
                "shelter_type": "COMMUNITY_CENTER",
                "latitude": 30.55,
                "longitude": 79.57,
                "total_capacity": 860,
                "effective_capacity": 690,
                "available_capacity": 260,
                "utilization_percentage": 62.3,
                "current_population": 430,
                "water_available_liters": 24400,
                "food_available_kg": 1810,
                "medical_kits_available": 18,
                "generator_fuel_liters": 130,
                "capacity_constraint": "NONE",
                "capacity_status": "AVAILABLE",
                "is_in_safe_zone": True,
                "safety_buffer_km": 12.6,
                "overall_suitability": "SUITABLE",
                "safety_score": 87.0,
                "has_generator": True,
                "has_medical_facility": True,
                "has_kitchen": True,
                "has_toilets": True,
                "access_road_status": "CLEAR",
                "geometry_wkt": "POINT(79.57 30.55)",
                "evaluation_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
            },
            {
                "shelter_id": "UK_SH_003",
                "state_code": "UK",
                "district_name": "Uttarkashi",
                "shelter_name": "Barkot Transit Shelter",
                "shelter_type": "GOVT_BUILDING",
                "latitude": 30.82,
                "longitude": 78.21,
                "total_capacity": 610,
                "effective_capacity": 420,
                "available_capacity": 100,
                "utilization_percentage": 76.2,
                "current_population": 320,
                "water_available_liters": 8600,
                "food_available_kg": 540,
                "medical_kits_available": 9,
                "generator_fuel_liters": 80,
                "capacity_constraint": "FOOD",
                "capacity_status": "LIMITED",
                "is_in_safe_zone": True,
                "safety_buffer_km": 8.9,
                "overall_suitability": "CONDITIONALLY_SUITABLE",
                "safety_score": 69.0,
                "has_generator": True,
                "has_medical_facility": False,
                "has_kitchen": True,
                "has_toilets": True,
                "access_road_status": "LIMITED",
                "geometry_wkt": "POINT(78.21 30.82)",
                "evaluation_timestamp": "2026-08-30T06:30:00+00:00",
                "model_version": "demo-scenario-1.0",
            },
        ],
    },
}


def list_scenarios() -> List[Dict[str, Any]]:
    return [
        {
            "scenario_id": scenario["scenario_id"],
            "name": scenario["name"],
            "description": scenario["description"],
            "geography": scenario["geography"],
            "hazard_mix": list(scenario["hazard_mix"]),
            "bbox": dict(scenario["bbox"]),
            "is_active": scenario_id == _ACTIVE_SCENARIO_ID,
        }
        for scenario_id, scenario in SCENARIOS.items()
    ]


def get_active_scenario() -> Dict[str, Any]:
    return SCENARIOS[_ACTIVE_SCENARIO_ID]


def activate_scenario(scenario_id: str) -> Dict[str, Any]:
    global _ACTIVE_SCENARIO_ID
    if scenario_id not in SCENARIOS:
        raise KeyError(f"Unknown scenario: {scenario_id}")
    _ACTIVE_SCENARIO_ID = scenario_id
    return get_active_scenario()


def _counter(rows: List[Dict[str, Any]], key: str) -> Dict[str, int]:
    return dict(Counter(str(row.get(key) or "UNKNOWN") for row in rows))


def build_demo_snapshot(
    south: float = INDIA_BBOX[0],
    west: float = INDIA_BBOX[1],
    north: float = INDIA_BBOX[2],
    east: float = INDIA_BBOX[3],
) -> Dict[str, Any]:
    scenario = deepcopy(get_active_scenario())
    red_zones = scenario["red_zones"]
    habitations = scenario["habitations"]
    shelters = scenario["shelters"]
    immediate = [h for h in habitations if h["priority_category"] == "IMMEDIATE"]
    worst = (
        max(red_zones, key=lambda row: float(row["risk_score"])) if red_zones else None
    )

    snapshot = {
        "mode": "DEMO_SCENARIO",
        "generated_at": _now(),
        "bbox": {"south": south, "west": west, "north": north, "east": east},
        "scenario": {
            "scenario_id": scenario["scenario_id"],
            "name": scenario["name"],
            "description": scenario["description"],
            "geography": scenario["geography"],
            "hazard_mix": list(scenario["hazard_mix"]),
            "bbox": dict(scenario["bbox"]),
        },
        "grid": {"nx": 0, "ny": 0, "cell_count": len(red_zones)},
        "data_sources": {
            "mode": "Curated SIH prototype scenario",
            "scenario_dataset": scenario["name"],
            "hazard_inputs": "Preloaded hazard polygons and risk drivers",
            "habitations": "Preloaded scenario habitations",
            "shelters": "Preloaded scenario shelters and carrying-capacity assumptions",
            "models": "Transparent scorecards operating on scenario data",
        },
        "alert": {
            "active": bool(red_zones),
            "headline": scenario["alert"]["headline"],
            "detail": scenario["alert"]["detail"],
            "worst_lat": worst["latitude"] if worst else None,
            "worst_lon": worst["longitude"] if worst else None,
            "worst_risk": worst["risk_score"] if worst else 0,
        },
        "summary": {
            "red_zone_count": len(red_zones),
            "habitation_count": len(habitations),
            "immediate_count": len(immediate),
            "short_term_count": len(
                [h for h in habitations if h["priority_category"] == "SHORT_TERM"]
            ),
            "medium_term_count": len(
                [h for h in habitations if h["priority_category"] == "MEDIUM_TERM"]
            ),
            "shelter_count": len(shelters),
            "safe_shelter_count": len([s for s in shelters if s["is_in_safe_zone"]]),
            "available_beds": sum(
                int(s["available_capacity"]) for s in shelters if s["is_in_safe_zone"]
            ),
            "population_immediate": sum(int(h["total_population"]) for h in immediate),
        },
        "red_zones": red_zones,
        "grid_cells": [
            {
                "latitude": z["latitude"],
                "longitude": z["longitude"],
                "risk_score": z["risk_score"],
                "is_red_zone": z["is_red_zone"],
                "hazard_type": z["hazard_type"],
                "precipitation_24h_mm": None,
                "elevation": None,
                "slope_percentage": None,
            }
            for z in red_zones
        ],
        "habitations": habitations,
        "shelters": shelters,
        "priority_mix": _counter(habitations, "priority_category"),
        "hazard_mix": _counter(red_zones, "hazard_type"),
        "cache_hit": False,
    }
    return snapshot


def inspect_demo_point(latitude: float, longitude: float) -> Dict[str, Any]:
    snapshot = build_demo_snapshot()
    zones = list(snapshot["red_zones"])
    shelters = list(snapshot["shelters"])
    if zones:
        nearest_zone = min(
            zones,
            key=lambda zone: _haversine_km(
                latitude, longitude, zone["latitude"], zone["longitude"]
            ),
        )
        zone_distance = _haversine_km(
            latitude, longitude, nearest_zone["latitude"], nearest_zone["longitude"]
        )
    else:
        nearest_zone = None
        zone_distance = 999.0

    nearest_shelter = None
    shelter_distance = None
    if shelters:
        nearest_shelter = min(
            shelters,
            key=lambda shelter: _haversine_km(
                latitude, longitude, shelter["latitude"], shelter["longitude"]
            ),
        )
        shelter_distance = _haversine_km(
            latitude,
            longitude,
            nearest_shelter["latitude"],
            nearest_shelter["longitude"],
        )

    if nearest_zone is None:
        risk_score = 18.0
        hazard_type = "LOW_RISK"
        risk_level = "LOW"
        urgency = "MEDIUM_TERM"
    else:
        decay = max(0.25, 1.0 - min(zone_distance, 25.0) / 35.0)
        risk_score = round(float(nearest_zone["risk_score"]) * decay, 2)
        hazard_type = nearest_zone["hazard_type"]
        risk_level = (
            "CRITICAL"
            if risk_score >= 85
            else "HIGH"
            if risk_score >= 65
            else "MEDIUM"
            if risk_score >= 40
            else "LOW"
        )
        urgency = (
            "IMMEDIATE"
            if risk_score >= 75
            else ("SHORT_TERM" if risk_score >= 50 else "MEDIUM_TERM")
        )

    return {
        "mode": "DEMO_SCENARIO",
        "scenario": snapshot["scenario"],
        "latitude": latitude,
        "longitude": longitude,
        "is_within_india": True,
        "risk_score": risk_score,
        "is_red_zone": risk_score >= 55,
        "risk_level": risk_level,
        "hazard_type": hazard_type,
        "urgency": urgency,
        "elevation": None,
        "slope_percentage": None,
        "precipitation_24h_mm": None,
        "precipitation_72h_mm": None,
        "soil_moisture_index": None,
        "temperature_celsius": None,
        "wind_speed_kmh": None,
        "humidity": None,
        "nearest_shelter": nearest_shelter,
        "nearest_shelter_km": round(shelter_distance, 2)
        if shelter_distance is not None
        else None,
        "red_zone_count_nearby": len(
            [
                z
                for z in zones
                if _haversine_km(latitude, longitude, z["latitude"], z["longitude"])
                <= 20.0
            ]
        ),
        "nearest_red_zone_distance_km": round(zone_distance, 2)
        if nearest_zone is not None
        else None,
        "model_version": "demo-scenario-1.0",
        "inspected_at": _now(),
        "data_sources": snapshot["data_sources"],
    }
